import "./globals.css";
import Link from "next/link";
export const metadata = {
  title: "Web Tutorials",
  description: "Generated by leanp",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          <li><Link href="/read/1">HTML</Link></li>
          <li><Link href="/read/2">CSS</Link></li>
        </ol>
        {children}
        <ul>
          <li><Link href="/create">create</Link></li>
          <li><Link href="/update">update</Link></li>
          <li><input type="button" value="delete"/></li>
        </ul>
      </body>
    </html>
  );
}
